name: Actions

on: [push, pull_request]

jobs:
  build:
    name: Build my project 
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Install ReSharper CLT
        uses: kasperhesthaven/setup-resharper-clt@v1.1.0
        with:
          resharper-version: "2020.3.3" # CLT Version to use, defaults to 2020.3.3

      - name: Clean up code
        run: cleanupcode.sh YourSolution.sln

      - name: Find duplicate code
        run: dupFinder.sh <source> -o=<PathToOutputFile>

      - name: Analyze code
        run: InspectCode.sh YourSolution.sln -o=<PathToOutputFile>

      # Cache
      - uses: actions/cache@v2
        with:
         path: Library
         key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
         restore-keys: |
          Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;enableCyclomaticComplexity;assemblyFilters:+my.assembly.*'

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts
          
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Coverage results
          path: artifacts